#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-07
# https://github.com/Aleksandr3Bocharov/refalabbrainfuck

RAYLIBCFLAGS="-Wall -O2"
RAYLIBLFLAGS="-lraylib -lm"

mkdir -p bin
$REFALABBIN/RefalAB src/RefalABBrainfuck_gui > RefalABBrainfuck_gui.log
as -o src/RefalABBrainfuck_gui.o src/RefalABBrainfuck_gui.s >> RefalABBrainfuck_gui.log
$REFALABBIN/RefalAB src/Interpretator >> RefalABBrainfuck_gui.log
as -o src/Interpretator.o src/Interpretator.s >> RefalABBrainfuck_gui.log
clang $REFALABCFLAGS -DPOSIX -I$REFALABINCLUDE -c src/Interpretatorc.c -o src/Interpretatorc.o >> RefalABBrainfuck_gui.log
clang $REFALABCFLAGS -DPOSIX -I$REFALABINCLUDE -c src/RefalABBrainfuckc_gui.c -o src/RefalABBrainfuckc_gui.o >> RefalABBrainfuck_gui.log
clang $RAYLIBCFLAGS -c src/gui.c -o src/gui.o >> RefalABBrainfuck_gui.log
clang -o bin/RefalABBrainfuck_gui src/RefalABBrainfuck_gui.o src/RefalABBrainfuckc_gui.o src/Interpretator.o src/Interpretatorc.o $REFALABLIB/obj/mainrf.o -L$REFALABLIB -lRefalAB src/gui.o $RAYLIBLFLAGS >> RefalABBrainfuck_gui.log
bin/RefalABBrainfuck_gui
