#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-17
# https://github.com/Aleksandr3Bocharov/refalabbrainfuck

mkdir -p bin
$REFALABBIN/refalab src/refalabbrainfuck -a,"-o refalabbrainfuck.o" > refalabbrainfuck.log
$REFALABBIN/refalab src/interpretator -a,"-o interpretator.o" >> refalabbrainfuck.log
clang $REFALABCFLAGS -DPOSIX -I$REFALABINCLUDE -c src/interpretatorc.c -o src/interpretatorc.o >> refalabbrainfuck.log
clang -o bin/refalabbrainfuck src/refalabbrainfuck.o src/interpretator.o src/interpretatorc.o $REFALABLIB/obj/mainrf.o -L$REFALABLIB -lrefalab >> refalabbrainfuck.log
bin/refalabbrainfuck $1
